// Generated by CoffeeScript 1.8.0

/** @jsx React.DOM */
var App, SearchBar, Song, SongList;

SearchBar = React.createClass({
  render: function() {
    return (
            <div className="search-bar">
                <input type="text" placeholder="Song name, artist, user, ..." ref="keyword" />
                <button>Search</button>
            </div>
        );
  }
});

SongList = React.createClass({
  render: function() {
    return (
            <div className="song-list">
                <Song />
            </div>
        );
  }
});

Song = React.createClass({
  render: function() {
    var Element;
    Element = (<div className="song">
                        <p className="title">Song name</p>
                        <p>
                            <span className="artist">Artist</span>
                            <span className="listen">000,000</span>
                        </p>
                    </div>);
    return (
            <div>
                {Element}
            </div>
        );
  }
});

App = React.createClass({
  getInitialState: function() {
    return {
      songList: []
    };
  },
  componentWillMount: function() {
    return this.nhacCuaTui = new NhacCuaTui();
  },
  render: function() {
    console.log(this.nhacCuaTui);
    return (
            <div id="wrapper">
                <SearchBar />
                <SongList />
            </div>
        );
  }
});

React.renderComponent(<App />, document.body);
