// Generated by CoffeeScript 1.8.0
var NhacCuaTui;

NhacCuaTui = function() {
  var _apiSettings, _yqlExecuteQuery;
  _apiSettings = {
    apiURL: "http://m.nhaccuatui.com/tim-kiem/bai-hat?q=",
    endpointURL: "https://query.yahooapis.com/v1/public/yql?q="
  };
  _yqlExecuteQuery = function(yqlStatement) {
    var yqlResult;
    yqlResult = {};
    $.ajax({
      url: "" + _apiSettings.endpointURL + (encodeURIComponent(yqlStatement)) + "&format=json",
      cache: false,
      async: false,
      success: function(response) {
        return yqlResult = response;
      },
      error: function(xmlHttpReq, ajaxOpts, error) {
        return console.log(error);
      }
    });
    return yqlResult;
  };
  this.search = function(keyword) {
    var result, yqlResult, yqlStatement;
    keyword = encodeURIComponent(keyword.trim());
    result = {
      status: false,
      items: []
    };
    if (keyword !== "") {
      yqlStatement = "SELECT * FROM html WHERE url='" + (_apiSettings.apiURL + keyword) + "' AND xpath='//div[contains(@class, \"bgmusic\")]'";
      yqlResult = _yqlExecuteQuery(yqlStatement);
      if (yqlResult.query.count > 0) {
        result.status = true;
        $.each(yqlResult.query.results.div, function(idx, item) {
          return result.items.push({
            title: song.h3.a.title,
            link: song.h3.a.href,
            artist: song.p.content,
            listen: song.p.span.content
          });
        });
      }
      return result;
    }
  };
  this.get = function(link) {
    var result, yqlResult, yqlStatement;
    result = {
      status: false,
      link: ""
    };
    if (link.trim() !== "") {
      yqlStatement = "SELECT * FROM html WHERE url='" + link + "' AND xpath='//div[@class=\"download\"]//'";
      yqlResult = _yqlExecuteQuery(yqlStatement);
      if (yqlResult.query.count > 0) {
        result = {
          status: true,
          link: yqlResult.query.results.a.href
        };
      }
    }
    return result;
  };
};
